"""add profile visibility settings

Revision ID: 061cfe347158
Revises: b860c5b4603b
Create Date: 2026-07-13 13:32:45.791740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061cfe347158'
down_revision: Union[str, None] = 'b860c5b4603b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default backfills the existing row(s) so the NOT NULL
    # constraint doesn't reject them - autogenerate leaves this out since
    # the model's default=True is Python-side only, not a DB default.
    op.add_column(
        'user_profiles', sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.true())
    )
    op.add_column('user_profiles', sa.Column('hidden_fields', sa.JSON(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'hidden_fields')
    op.drop_column('user_profiles', 'is_public')
    # ### end Alembic commands ###
