"""add reservation hardware_started_at

Revision ID: 99aa7a7332c9
Revises: 11747eff667e
Create Date: 2026-07-23 11:46:43.522013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99aa7a7332c9'
down_revision: Union[str, None] = '11747eff667e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('hardware_started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'hardware_started_at')
    # ### end Alembic commands ###
